2016-05-22 08:42:37 Error: Fatal Error (64): Cannot redeclare UsersController::$components in [C:\xampp\htdocs\test\app\Controller\UsersController.php, line 125]
2016-05-22 08:42:37 Error: [FatalErrorException] Cannot redeclare UsersController::$components
Request URL: /test/users/login
Stack Trace:
#0 C:\xampp\htdocs\test\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(64, 'Cannot redeclar...', 'C:\\xampp\\htdocs...', 125)
#1 [internal function]: ErrorHandler::handleError(64, 'Cannot redeclar...', 'C:\\xampp\\htdocs...', 125, Array)
#2 C:\xampp\htdocs\test\lib\Cake\Core\App.php(933): call_user_func('ErrorHandler::h...', 64, 'Cannot redeclar...', 'C:\\xampp\\htdocs...', 125, Array)
#3 C:\xampp\htdocs\test\lib\Cake\Core\App.php(906): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2016-05-22 08:44:15 Error: [MissingActionException] Action UsersController::forgetpw.ctp() could not be found.
Exception Attributes: array (
  'controller' => 'UsersController',
  'action' => 'forgetpw.ctp',
)
Request URL: /test/users/forgetpw.ctp
Stack Trace:
#0 C:\xampp\htdocs\test\lib\Cake\Routing\Dispatcher.php(193): Controller->invokeAction(Object(CakeRequest))
#1 C:\xampp\htdocs\test\lib\Cake\Routing\Dispatcher.php(167): Dispatcher->_invoke(Object(UsersController), Object(CakeRequest))
#2 C:\xampp\htdocs\test\app\webroot\index.php(118): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#3 {main}
2016-05-22 19:18:47 Error: Fatal Error (4): syntax error, unexpected ';' in [C:\xampp\htdocs\test\app\View\Layouts\default.ctp, line 56]
2016-05-22 19:18:47 Error: [FatalErrorException] syntax error, unexpected ';'
Request URL: /test/Posts
Stack Trace:
#0 C:\xampp\htdocs\test\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 56)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 56, Array)
#2 C:\xampp\htdocs\test\lib\Cake\Core\App.php(933): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 56, Array)
#3 C:\xampp\htdocs\test\lib\Cake\Core\App.php(906): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2016-05-22 20:00:01 Error: Fatal Error (4): syntax error, unexpected 'endforeach' (T_ENDFOREACH) in [C:\xampp\htdocs\test\app\View\Posts\visitors.ctp, line 15]
2016-05-22 20:00:01 Error: [FatalErrorException] syntax error, unexpected 'endforeach' (T_ENDFOREACH)
Request URL: /test/
Stack Trace:
#0 C:\xampp\htdocs\test\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 15)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 15, Array)
#2 C:\xampp\htdocs\test\lib\Cake\Core\App.php(933): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 15, Array)
#3 C:\xampp\htdocs\test\lib\Cake\Core\App.php(906): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2016-05-22 20:01:05 Error: Fatal Error (4): syntax error, unexpected 'endforeach' (T_ENDFOREACH) in [C:\xampp\htdocs\test\app\View\Posts\visitors.ctp, line 17]
2016-05-22 20:01:05 Error: [FatalErrorException] syntax error, unexpected 'endforeach' (T_ENDFOREACH)
Request URL: /test/
Stack Trace:
#0 C:\xampp\htdocs\test\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 17)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 17, Array)
#2 C:\xampp\htdocs\test\lib\Cake\Core\App.php(933): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 17, Array)
#3 C:\xampp\htdocs\test\lib\Cake\Core\App.php(906): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2016-05-22 21:15:16 Error: [NotFoundException] Invalid user
Request URL: /test/users/view
Stack Trace:
#0 [internal function]: UsersController->view()
#1 C:\xampp\htdocs\test\lib\Cake\Controller\Controller.php(490): ReflectionMethod->invokeArgs(Object(UsersController), Array)
#2 C:\xampp\htdocs\test\lib\Cake\Routing\Dispatcher.php(193): Controller->invokeAction(Object(CakeRequest))
#3 C:\xampp\htdocs\test\lib\Cake\Routing\Dispatcher.php(167): Dispatcher->_invoke(Object(UsersController), Object(CakeRequest))
#4 C:\xampp\htdocs\test\app\webroot\index.php(118): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#5 {main}
2016-05-22 21:35:46 Error: [NotFoundException] Invalid user
Request URL: /test/users
Stack Trace:
#0 [internal function]: UsersController->index()
#1 C:\xampp\htdocs\test\lib\Cake\Controller\Controller.php(490): ReflectionMethod->invokeArgs(Object(UsersController), Array)
#2 C:\xampp\htdocs\test\lib\Cake\Routing\Dispatcher.php(193): Controller->invokeAction(Object(CakeRequest))
#3 C:\xampp\htdocs\test\lib\Cake\Routing\Dispatcher.php(167): Dispatcher->_invoke(Object(UsersController), Object(CakeRequest))
#4 C:\xampp\htdocs\test\app\webroot\index.php(118): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#5 {main}
2016-05-22 21:38:49 Error: [NotFoundException] Invalid user
Request URL: /test/users
Stack Trace:
#0 [internal function]: UsersController->index()
#1 C:\xampp\htdocs\test\lib\Cake\Controller\Controller.php(490): ReflectionMethod->invokeArgs(Object(UsersController), Array)
#2 C:\xampp\htdocs\test\lib\Cake\Routing\Dispatcher.php(193): Controller->invokeAction(Object(CakeRequest))
#3 C:\xampp\htdocs\test\lib\Cake\Routing\Dispatcher.php(167): Dispatcher->_invoke(Object(UsersController), Object(CakeRequest))
#4 C:\xampp\htdocs\test\app\webroot\index.php(118): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#5 {main}
2016-05-22 21:39:05 Error: [NotFoundException] Invalid user
Request URL: /test/users/index/1
Stack Trace:
#0 [internal function]: UsersController->index('1')
#1 C:\xampp\htdocs\test\lib\Cake\Controller\Controller.php(490): ReflectionMethod->invokeArgs(Object(UsersController), Array)
#2 C:\xampp\htdocs\test\lib\Cake\Routing\Dispatcher.php(193): Controller->invokeAction(Object(CakeRequest))
#3 C:\xampp\htdocs\test\lib\Cake\Routing\Dispatcher.php(167): Dispatcher->_invoke(Object(UsersController), Object(CakeRequest))
#4 C:\xampp\htdocs\test\app\webroot\index.php(118): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#5 {main}
2016-05-22 21:49:25 Error: [NotFoundException] Invalid user
Request URL: /test/users
Stack Trace:
#0 [internal function]: UsersController->index()
#1 C:\xampp\htdocs\test\lib\Cake\Controller\Controller.php(490): ReflectionMethod->invokeArgs(Object(UsersController), Array)
#2 C:\xampp\htdocs\test\lib\Cake\Routing\Dispatcher.php(193): Controller->invokeAction(Object(CakeRequest))
#3 C:\xampp\htdocs\test\lib\Cake\Routing\Dispatcher.php(167): Dispatcher->_invoke(Object(UsersController), Object(CakeRequest))
#4 C:\xampp\htdocs\test\app\webroot\index.php(118): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#5 {main}
2016-05-22 21:49:36 Error: [MissingControllerException] Controller class ViewController could not be found.
Exception Attributes: array (
  'class' => 'ViewController',
  'plugin' => NULL,
)
Request URL: /test/view/1
Stack Trace:
#0 C:\xampp\htdocs\test\app\webroot\index.php(118): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#1 {main}
2016-05-22 21:49:50 Error: [NotFoundException] Invalid user
Request URL: /test/users/view/1
Stack Trace:
#0 [internal function]: UsersController->view('1')
#1 C:\xampp\htdocs\test\lib\Cake\Controller\Controller.php(490): ReflectionMethod->invokeArgs(Object(UsersController), Array)
#2 C:\xampp\htdocs\test\lib\Cake\Routing\Dispatcher.php(193): Controller->invokeAction(Object(CakeRequest))
#3 C:\xampp\htdocs\test\lib\Cake\Routing\Dispatcher.php(167): Dispatcher->_invoke(Object(UsersController), Object(CakeRequest))
#4 C:\xampp\htdocs\test\app\webroot\index.php(118): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#5 {main}
2016-05-22 21:50:23 Error: [NotFoundException] Invalid user
Request URL: /test/users/view
Stack Trace:
#0 [internal function]: UsersController->view()
#1 C:\xampp\htdocs\test\lib\Cake\Controller\Controller.php(490): ReflectionMethod->invokeArgs(Object(UsersController), Array)
#2 C:\xampp\htdocs\test\lib\Cake\Routing\Dispatcher.php(193): Controller->invokeAction(Object(CakeRequest))
#3 C:\xampp\htdocs\test\lib\Cake\Routing\Dispatcher.php(167): Dispatcher->_invoke(Object(UsersController), Object(CakeRequest))
#4 C:\xampp\htdocs\test\app\webroot\index.php(118): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#5 {main}
2016-05-22 21:57:47 Error: [NotFoundException] Invalid user
Request URL: /test/users/view
Stack Trace:
#0 [internal function]: UsersController->view()
#1 C:\xampp\htdocs\test\lib\Cake\Controller\Controller.php(490): ReflectionMethod->invokeArgs(Object(UsersController), Array)
#2 C:\xampp\htdocs\test\lib\Cake\Routing\Dispatcher.php(193): Controller->invokeAction(Object(CakeRequest))
#3 C:\xampp\htdocs\test\lib\Cake\Routing\Dispatcher.php(167): Dispatcher->_invoke(Object(UsersController), Object(CakeRequest))
#4 C:\xampp\htdocs\test\app\webroot\index.php(118): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#5 {main}
2016-05-22 22:59:25 Error: Fatal Error (1): Call to a member function find() on null in [C:\xampp\htdocs\test\app\Controller\UsersController.php, line 114]
2016-05-22 22:59:25 Error: [FatalErrorException] Call to a member function find() on null
Request URL: /test/Users/login
Stack Trace:
#0 C:\xampp\htdocs\test\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 114)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 114, Array)
#2 C:\xampp\htdocs\test\lib\Cake\Core\App.php(933): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 114, Array)
#3 C:\xampp\htdocs\test\lib\Cake\Core\App.php(906): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2016-05-22 23:03:34 Error: [NotFoundException] Invalid user
Request URL: /test/users/view
Stack Trace:
#0 [internal function]: UsersController->view()
#1 C:\xampp\htdocs\test\lib\Cake\Controller\Controller.php(490): ReflectionMethod->invokeArgs(Object(UsersController), Array)
#2 C:\xampp\htdocs\test\lib\Cake\Routing\Dispatcher.php(193): Controller->invokeAction(Object(CakeRequest))
#3 C:\xampp\htdocs\test\lib\Cake\Routing\Dispatcher.php(167): Dispatcher->_invoke(Object(UsersController), Object(CakeRequest))
#4 C:\xampp\htdocs\test\app\webroot\index.php(118): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#5 {main}
2016-05-22 23:03:46 Error: [NotFoundException] Invalid user
Request URL: /test/users/view
Stack Trace:
#0 [internal function]: UsersController->view()
#1 C:\xampp\htdocs\test\lib\Cake\Controller\Controller.php(490): ReflectionMethod->invokeArgs(Object(UsersController), Array)
#2 C:\xampp\htdocs\test\lib\Cake\Routing\Dispatcher.php(193): Controller->invokeAction(Object(CakeRequest))
#3 C:\xampp\htdocs\test\lib\Cake\Routing\Dispatcher.php(167): Dispatcher->_invoke(Object(UsersController), Object(CakeRequest))
#4 C:\xampp\htdocs\test\app\webroot\index.php(118): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#5 {main}
2016-05-22 23:05:25 Error: [NotFoundException] Invalid user
Request URL: /test/users/view
Stack Trace:
#0 [internal function]: UsersController->view()
#1 C:\xampp\htdocs\test\lib\Cake\Controller\Controller.php(490): ReflectionMethod->invokeArgs(Object(UsersController), Array)
#2 C:\xampp\htdocs\test\lib\Cake\Routing\Dispatcher.php(193): Controller->invokeAction(Object(CakeRequest))
#3 C:\xampp\htdocs\test\lib\Cake\Routing\Dispatcher.php(167): Dispatcher->_invoke(Object(UsersController), Object(CakeRequest))
#4 C:\xampp\htdocs\test\app\webroot\index.php(118): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#5 {main}
2016-05-22 23:34:06 Error: [NotFoundException] Invalid user
Request URL: /test/users/login
Stack Trace:
#0 [internal function]: UsersController->login()
#1 C:\xampp\htdocs\test\lib\Cake\Controller\Controller.php(490): ReflectionMethod->invokeArgs(Object(UsersController), Array)
#2 C:\xampp\htdocs\test\lib\Cake\Routing\Dispatcher.php(193): Controller->invokeAction(Object(CakeRequest))
#3 C:\xampp\htdocs\test\lib\Cake\Routing\Dispatcher.php(167): Dispatcher->_invoke(Object(UsersController), Object(CakeRequest))
#4 C:\xampp\htdocs\test\app\webroot\index.php(118): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#5 {main}
2016-05-22 23:48:46 Error: [NotFoundException] Invalid user
Request URL: /test/users/view
Stack Trace:
#0 [internal function]: UsersController->view()
#1 C:\xampp\htdocs\test\lib\Cake\Controller\Controller.php(490): ReflectionMethod->invokeArgs(Object(UsersController), Array)
#2 C:\xampp\htdocs\test\lib\Cake\Routing\Dispatcher.php(193): Controller->invokeAction(Object(CakeRequest))
#3 C:\xampp\htdocs\test\lib\Cake\Routing\Dispatcher.php(167): Dispatcher->_invoke(Object(UsersController), Object(CakeRequest))
#4 C:\xampp\htdocs\test\app\webroot\index.php(118): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#5 {main}
2016-05-22 23:50:21 Error: [NotFoundException] Invalid user
Request URL: /test/users/view/1
Stack Trace:
#0 [internal function]: UsersController->view('1')
#1 C:\xampp\htdocs\test\lib\Cake\Controller\Controller.php(490): ReflectionMethod->invokeArgs(Object(UsersController), Array)
#2 C:\xampp\htdocs\test\lib\Cake\Routing\Dispatcher.php(193): Controller->invokeAction(Object(CakeRequest))
#3 C:\xampp\htdocs\test\lib\Cake\Routing\Dispatcher.php(167): Dispatcher->_invoke(Object(UsersController), Object(CakeRequest))
#4 C:\xampp\htdocs\test\app\webroot\index.php(118): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#5 {main}
2016-05-22 23:50:49 Error: [NotFoundException] Invalid user
Request URL: /test/users/view/1
Stack Trace:
#0 [internal function]: UsersController->view('1')
#1 C:\xampp\htdocs\test\lib\Cake\Controller\Controller.php(490): ReflectionMethod->invokeArgs(Object(UsersController), Array)
#2 C:\xampp\htdocs\test\lib\Cake\Routing\Dispatcher.php(193): Controller->invokeAction(Object(CakeRequest))
#3 C:\xampp\htdocs\test\lib\Cake\Routing\Dispatcher.php(167): Dispatcher->_invoke(Object(UsersController), Object(CakeRequest))
#4 C:\xampp\htdocs\test\app\webroot\index.php(118): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#5 {main}
2016-05-23 00:13:37 Error: [NotFoundException] Invalid user
Request URL: /test/users/edit/13
Stack Trace:
#0 [internal function]: UsersController->edit('13')
#1 C:\xampp\htdocs\test\lib\Cake\Controller\Controller.php(490): ReflectionMethod->invokeArgs(Object(UsersController), Array)
#2 C:\xampp\htdocs\test\lib\Cake\Routing\Dispatcher.php(193): Controller->invokeAction(Object(CakeRequest))
#3 C:\xampp\htdocs\test\lib\Cake\Routing\Dispatcher.php(167): Dispatcher->_invoke(Object(UsersController), Object(CakeRequest))
#4 C:\xampp\htdocs\test\app\webroot\index.php(118): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#5 {main}
2016-05-23 00:13:59 Error: [NotFoundException] Invalid user
Request URL: /test/users/view/13
Stack Trace:
#0 [internal function]: UsersController->view('13')
#1 C:\xampp\htdocs\test\lib\Cake\Controller\Controller.php(490): ReflectionMethod->invokeArgs(Object(UsersController), Array)
#2 C:\xampp\htdocs\test\lib\Cake\Routing\Dispatcher.php(193): Controller->invokeAction(Object(CakeRequest))
#3 C:\xampp\htdocs\test\lib\Cake\Routing\Dispatcher.php(167): Dispatcher->_invoke(Object(UsersController), Object(CakeRequest))
#4 C:\xampp\htdocs\test\app\webroot\index.php(118): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#5 {main}
2016-05-23 00:14:17 Error: [NotFoundException] Invalid user
Request URL: /test/users/view/13
Stack Trace:
#0 [internal function]: UsersController->view('13')
#1 C:\xampp\htdocs\test\lib\Cake\Controller\Controller.php(490): ReflectionMethod->invokeArgs(Object(UsersController), Array)
#2 C:\xampp\htdocs\test\lib\Cake\Routing\Dispatcher.php(193): Controller->invokeAction(Object(CakeRequest))
#3 C:\xampp\htdocs\test\lib\Cake\Routing\Dispatcher.php(167): Dispatcher->_invoke(Object(UsersController), Object(CakeRequest))
#4 C:\xampp\htdocs\test\app\webroot\index.php(118): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#5 {main}
2016-05-23 00:15:19 Error: [NotFoundException] Invalid user
Request URL: /test/users/view/13
Stack Trace:
#0 [internal function]: UsersController->view('13')
#1 C:\xampp\htdocs\test\lib\Cake\Controller\Controller.php(490): ReflectionMethod->invokeArgs(Object(UsersController), Array)
#2 C:\xampp\htdocs\test\lib\Cake\Routing\Dispatcher.php(193): Controller->invokeAction(Object(CakeRequest))
#3 C:\xampp\htdocs\test\lib\Cake\Routing\Dispatcher.php(167): Dispatcher->_invoke(Object(UsersController), Object(CakeRequest))
#4 C:\xampp\htdocs\test\app\webroot\index.php(118): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#5 {main}
2016-05-23 00:16:58 Error: [NotFoundException] Invalid user
Request URL: /test/users/view/13
Stack Trace:
#0 [internal function]: UsersController->view('13')
#1 C:\xampp\htdocs\test\lib\Cake\Controller\Controller.php(490): ReflectionMethod->invokeArgs(Object(UsersController), Array)
#2 C:\xampp\htdocs\test\lib\Cake\Routing\Dispatcher.php(193): Controller->invokeAction(Object(CakeRequest))
#3 C:\xampp\htdocs\test\lib\Cake\Routing\Dispatcher.php(167): Dispatcher->_invoke(Object(UsersController), Object(CakeRequest))
#4 C:\xampp\htdocs\test\app\webroot\index.php(118): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#5 {main}
2016-05-23 00:17:12 Error: [NotFoundException] Invalid user
Request URL: /test/users/view/13
Stack Trace:
#0 [internal function]: UsersController->view('13')
#1 C:\xampp\htdocs\test\lib\Cake\Controller\Controller.php(490): ReflectionMethod->invokeArgs(Object(UsersController), Array)
#2 C:\xampp\htdocs\test\lib\Cake\Routing\Dispatcher.php(193): Controller->invokeAction(Object(CakeRequest))
#3 C:\xampp\htdocs\test\lib\Cake\Routing\Dispatcher.php(167): Dispatcher->_invoke(Object(UsersController), Object(CakeRequest))
#4 C:\xampp\htdocs\test\app\webroot\index.php(118): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#5 {main}
2016-05-23 00:17:36 Error: [NotFoundException] Invalid user
Request URL: /test/users/view/13
Stack Trace:
#0 [internal function]: UsersController->view('13')
#1 C:\xampp\htdocs\test\lib\Cake\Controller\Controller.php(490): ReflectionMethod->invokeArgs(Object(UsersController), Array)
#2 C:\xampp\htdocs\test\lib\Cake\Routing\Dispatcher.php(193): Controller->invokeAction(Object(CakeRequest))
#3 C:\xampp\htdocs\test\lib\Cake\Routing\Dispatcher.php(167): Dispatcher->_invoke(Object(UsersController), Object(CakeRequest))
#4 C:\xampp\htdocs\test\app\webroot\index.php(118): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#5 {main}
2016-05-23 00:20:13 Error: [NotFoundException] Invalid user
Request URL: /test/users/view/13
Stack Trace:
#0 [internal function]: UsersController->view('13')
#1 C:\xampp\htdocs\test\lib\Cake\Controller\Controller.php(490): ReflectionMethod->invokeArgs(Object(UsersController), Array)
#2 C:\xampp\htdocs\test\lib\Cake\Routing\Dispatcher.php(193): Controller->invokeAction(Object(CakeRequest))
#3 C:\xampp\htdocs\test\lib\Cake\Routing\Dispatcher.php(167): Dispatcher->_invoke(Object(UsersController), Object(CakeRequest))
#4 C:\xampp\htdocs\test\app\webroot\index.php(118): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#5 {main}
2016-05-23 00:26:52 Error: [NotFoundException] Invalid user
Request URL: /test/users/view/%3Cdiv%20class=%22input%20text%22%3E%3Clabel%20for=%22id%22%3EId%3C/label%3E%3Cinput%20name=%22data[id]%22%20type=%22text%22%20id=%22id%22/%3E%3C/div%3E
Stack Trace:
#0 [internal function]: UsersController->view('<div class="inp...', 'label><input na...', '><', 'div>')
#1 C:\xampp\htdocs\test\lib\Cake\Controller\Controller.php(490): ReflectionMethod->invokeArgs(Object(UsersController), Array)
#2 C:\xampp\htdocs\test\lib\Cake\Routing\Dispatcher.php(193): Controller->invokeAction(Object(CakeRequest))
#3 C:\xampp\htdocs\test\lib\Cake\Routing\Dispatcher.php(167): Dispatcher->_invoke(Object(UsersController), Object(CakeRequest))
#4 C:\xampp\htdocs\test\app\webroot\index.php(118): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#5 {main}
2016-05-23 01:33:25 Error: [NotFoundException] Invalid user
Request URL: /test/users
Stack Trace:
#0 [internal function]: UsersController->index()
#1 C:\xampp\htdocs\test\lib\Cake\Controller\Controller.php(490): ReflectionMethod->invokeArgs(Object(UsersController), Array)
#2 C:\xampp\htdocs\test\lib\Cake\Routing\Dispatcher.php(193): Controller->invokeAction(Object(CakeRequest))
#3 C:\xampp\htdocs\test\lib\Cake\Routing\Dispatcher.php(167): Dispatcher->_invoke(Object(UsersController), Object(CakeRequest))
#4 C:\xampp\htdocs\test\app\webroot\index.php(118): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#5 {main}
2016-05-23 06:00:10 Error: [NotFoundException] Invalid user
Request URL: /test/users
Stack Trace:
#0 [internal function]: UsersController->index()
#1 C:\xampp\htdocs\test\lib\Cake\Controller\Controller.php(490): ReflectionMethod->invokeArgs(Object(UsersController), Array)
#2 C:\xampp\htdocs\test\lib\Cake\Routing\Dispatcher.php(193): Controller->invokeAction(Object(CakeRequest))
#3 C:\xampp\htdocs\test\lib\Cake\Routing\Dispatcher.php(167): Dispatcher->_invoke(Object(UsersController), Object(CakeRequest))
#4 C:\xampp\htdocs\test\app\webroot\index.php(118): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#5 {main}
2016-05-23 06:00:21 Error: [MissingTableException] Table posts for model Post was not found in datasource default.
Exception Attributes: array (
  'table' => 'posts',
  'class' => 'Post',
  'ds' => 'default',
)
Request URL: /test/
Stack Trace:
#0 C:\xampp\htdocs\test\lib\Cake\Model\Model.php(3644): Model->setSource('posts')
#1 C:\xampp\htdocs\test\lib\Cake\Model\Model.php(3022): Model->getDataSource()
#2 C:\xampp\htdocs\test\lib\Cake\Model\Model.php(2994): Model->_readDataSource('all', Array)
#3 C:\xampp\htdocs\test\lib\Cake\Controller\Component\PaginatorComponent.php(196): Model->find('all', Array)
#4 C:\xampp\htdocs\test\app\Controller\PostsController.php(30): PaginatorComponent->paginate()
#5 [internal function]: PostsController->visitors()
#6 C:\xampp\htdocs\test\lib\Cake\Controller\Controller.php(490): ReflectionMethod->invokeArgs(Object(PostsController), Array)
#7 C:\xampp\htdocs\test\lib\Cake\Routing\Dispatcher.php(193): Controller->invokeAction(Object(CakeRequest))
#8 C:\xampp\htdocs\test\lib\Cake\Routing\Dispatcher.php(167): Dispatcher->_invoke(Object(PostsController), Object(CakeRequest))
#9 C:\xampp\htdocs\test\app\webroot\index.php(118): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#10 {main}
2016-05-23 06:00:45 Error: [MissingTableException] Table posts for model Post was not found in datasource default.
Exception Attributes: array (
  'table' => 'posts',
  'class' => 'Post',
  'ds' => 'default',
)
Request URL: /test/
Stack Trace:
#0 C:\xampp\htdocs\test\lib\Cake\Model\Model.php(3644): Model->setSource('posts')
#1 C:\xampp\htdocs\test\lib\Cake\Model\Model.php(3022): Model->getDataSource()
#2 C:\xampp\htdocs\test\lib\Cake\Model\Model.php(2994): Model->_readDataSource('all', Array)
#3 C:\xampp\htdocs\test\lib\Cake\Controller\Component\PaginatorComponent.php(196): Model->find('all', Array)
#4 C:\xampp\htdocs\test\app\Controller\PostsController.php(30): PaginatorComponent->paginate()
#5 [internal function]: PostsController->visitors()
#6 C:\xampp\htdocs\test\lib\Cake\Controller\Controller.php(490): ReflectionMethod->invokeArgs(Object(PostsController), Array)
#7 C:\xampp\htdocs\test\lib\Cake\Routing\Dispatcher.php(193): Controller->invokeAction(Object(CakeRequest))
#8 C:\xampp\htdocs\test\lib\Cake\Routing\Dispatcher.php(167): Dispatcher->_invoke(Object(PostsController), Object(CakeRequest))
#9 C:\xampp\htdocs\test\app\webroot\index.php(118): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#10 {main}
2016-05-23 06:05:18 Error: [NotFoundException] Invalid user
Request URL: /test/users/view
Stack Trace:
#0 [internal function]: UsersController->view()
#1 C:\xampp\htdocs\test\lib\Cake\Controller\Controller.php(490): ReflectionMethod->invokeArgs(Object(UsersController), Array)
#2 C:\xampp\htdocs\test\lib\Cake\Routing\Dispatcher.php(193): Controller->invokeAction(Object(CakeRequest))
#3 C:\xampp\htdocs\test\lib\Cake\Routing\Dispatcher.php(167): Dispatcher->_invoke(Object(UsersController), Object(CakeRequest))
#4 C:\xampp\htdocs\test\app\webroot\index.php(118): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#5 {main}
2016-05-23 06:36:17 Error: [MissingActionException] Action PostsController::visitors() could not be found.
Exception Attributes: array (
  'controller' => 'PostsController',
  'action' => 'visitors',
)
Request URL: /test/
Stack Trace:
#0 C:\xampp\htdocs\test\lib\Cake\Routing\Dispatcher.php(193): Controller->invokeAction(Object(CakeRequest))
#1 C:\xampp\htdocs\test\lib\Cake\Routing\Dispatcher.php(167): Dispatcher->_invoke(Object(PostsController), Object(CakeRequest))
#2 C:\xampp\htdocs\test\app\webroot\index.php(118): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#3 {main}
2016-05-23 06:36:17 Error: [MissingActionException] Action PostsController::visitors() could not be found.
Exception Attributes: array (
  'controller' => 'PostsController',
  'action' => 'visitors',
)
Request URL: /test/
Stack Trace:
#0 C:\xampp\htdocs\test\lib\Cake\Routing\Dispatcher.php(193): Controller->invokeAction(Object(CakeRequest))
#1 C:\xampp\htdocs\test\lib\Cake\Routing\Dispatcher.php(167): Dispatcher->_invoke(Object(PostsController), Object(CakeRequest))
#2 C:\xampp\htdocs\test\app\webroot\index.php(118): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#3 {main}
2016-05-23 08:00:36 Error: Fatal Error (4): syntax error, unexpected ')', expecting ',' or ';' in [C:\xampp\htdocs\test\app\View\Users\login.ctp, line 4]
2016-05-23 08:00:36 Error: [FatalErrorException] syntax error, unexpected ')', expecting ',' or ';'
Request URL: /test/users/login
Stack Trace:
#0 C:\xampp\htdocs\test\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 4)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 4, Array)
#2 C:\xampp\htdocs\test\lib\Cake\Core\App.php(933): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 4, Array)
#3 C:\xampp\htdocs\test\lib\Cake\Core\App.php(906): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2016-05-23 11:07:44 Error: [MissingViewException] View file "Users\list_users.ctp" is missing.
Exception Attributes: array (
  'file' => 'Users\\list_users.ctp',
)
Request URL: /test/users/listUsers/23
Stack Trace:
#0 C:\xampp\htdocs\test\lib\Cake\View\View.php(470): View->_getViewFileName(NULL)
#1 C:\xampp\htdocs\test\lib\Cake\Controller\Controller.php(960): View->render(NULL, NULL)
#2 C:\xampp\htdocs\test\lib\Cake\Routing\Dispatcher.php(200): Controller->render()
#3 C:\xampp\htdocs\test\lib\Cake\Routing\Dispatcher.php(167): Dispatcher->_invoke(Object(UsersController), Object(CakeRequest))
#4 C:\xampp\htdocs\test\app\webroot\index.php(118): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#5 {main}
2016-05-23 11:09:27 Error: [MissingViewException] View file "Users\list_users.ctp" is missing.
Exception Attributes: array (
  'file' => 'Users\\list_users.ctp',
)
Request URL: /test/users/listUsers/23
Stack Trace:
#0 C:\xampp\htdocs\test\lib\Cake\View\View.php(470): View->_getViewFileName(NULL)
#1 C:\xampp\htdocs\test\lib\Cake\Controller\Controller.php(960): View->render(NULL, NULL)
#2 C:\xampp\htdocs\test\lib\Cake\Routing\Dispatcher.php(200): Controller->render()
#3 C:\xampp\htdocs\test\lib\Cake\Routing\Dispatcher.php(167): Dispatcher->_invoke(Object(UsersController), Object(CakeRequest))
#4 C:\xampp\htdocs\test\app\webroot\index.php(118): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#5 {main}
2016-05-23 11:09:35 Error: [MissingViewException] View file "Users\list_users.ctp" is missing.
Exception Attributes: array (
  'file' => 'Users\\list_users.ctp',
)
Request URL: /test/users/listUsers/
Stack Trace:
#0 C:\xampp\htdocs\test\lib\Cake\View\View.php(470): View->_getViewFileName(NULL)
#1 C:\xampp\htdocs\test\lib\Cake\Controller\Controller.php(960): View->render(NULL, NULL)
#2 C:\xampp\htdocs\test\lib\Cake\Routing\Dispatcher.php(200): Controller->render()
#3 C:\xampp\htdocs\test\lib\Cake\Routing\Dispatcher.php(167): Dispatcher->_invoke(Object(UsersController), Object(CakeRequest))
#4 C:\xampp\htdocs\test\app\webroot\index.php(118): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#5 {main}
2016-05-23 11:26:48 Error: Fatal Error (1): Call to a member function create() on null in [C:\xampp\htdocs\test\app\View\Users\list_users.ctp, line 42]
2016-05-23 11:26:48 Error: [FatalErrorException] Call to a member function create() on null
Request URL: /test/users/listUsers
Stack Trace:
#0 C:\xampp\htdocs\test\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 42)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 42, Array)
#2 C:\xampp\htdocs\test\lib\Cake\Core\App.php(933): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 42, Array)
#3 C:\xampp\htdocs\test\lib\Cake\Core\App.php(906): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2016-05-23 11:28:45 Error: Fatal Error (1): Call to a member function create() on null in [C:\xampp\htdocs\test\app\View\Users\list_users.ctp, line 42]
2016-05-23 11:28:45 Error: [FatalErrorException] Call to a member function create() on null
Request URL: /test/users/listUsers
Stack Trace:
#0 C:\xampp\htdocs\test\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 42)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 42, Array)
#2 C:\xampp\htdocs\test\lib\Cake\Core\App.php(933): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 42, Array)
#3 C:\xampp\htdocs\test\lib\Cake\Core\App.php(906): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2016-05-23 11:32:08 Error: [MissingActionException] Action UsersController::search.ctp() could not be found.
Exception Attributes: array (
  'controller' => 'UsersController',
  'action' => 'search.ctp',
)
Request URL: /test/users/search.ctp
Stack Trace:
#0 C:\xampp\htdocs\test\lib\Cake\Routing\Dispatcher.php(193): Controller->invokeAction(Object(CakeRequest))
#1 C:\xampp\htdocs\test\lib\Cake\Routing\Dispatcher.php(167): Dispatcher->_invoke(Object(UsersController), Object(CakeRequest))
#2 C:\xampp\htdocs\test\app\webroot\index.php(118): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#3 {main}
2016-05-23 11:36:07 Error: Fatal Error (1): Call to a member function create() on null in [C:\xampp\htdocs\test\app\View\Users\list_users.ctp, line 40]
2016-05-23 11:36:07 Error: [FatalErrorException] Call to a member function create() on null
Request URL: /test/users/listUsers
Stack Trace:
#0 C:\xampp\htdocs\test\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 40)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 40, Array)
#2 C:\xampp\htdocs\test\lib\Cake\Core\App.php(933): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 40, Array)
#3 C:\xampp\htdocs\test\lib\Cake\Core\App.php(906): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2016-05-23 11:38:35 Error: Fatal Error (1): Call to a member function create() on null in [C:\xampp\htdocs\test\app\View\Users\list_users.ctp, line 40]
2016-05-23 11:38:35 Error: [FatalErrorException] Call to a member function create() on null
Request URL: /test/users/listUsers
Stack Trace:
#0 C:\xampp\htdocs\test\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 40)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 40, Array)
#2 C:\xampp\htdocs\test\lib\Cake\Core\App.php(933): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 40, Array)
#3 C:\xampp\htdocs\test\lib\Cake\Core\App.php(906): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2016-05-23 11:39:00 Error: Fatal Error (1): Call to a member function create() on null in [C:\xampp\htdocs\test\app\View\Users\list_users.ctp, line 40]
2016-05-23 11:39:00 Error: [FatalErrorException] Call to a member function create() on null
Request URL: /test/users/listUsers
Stack Trace:
#0 C:\xampp\htdocs\test\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 40)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 40, Array)
#2 C:\xampp\htdocs\test\lib\Cake\Core\App.php(933): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 40, Array)
#3 C:\xampp\htdocs\test\lib\Cake\Core\App.php(906): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2016-05-23 11:40:53 Error: Fatal Error (1): Call to a member function create() on null in [C:\xampp\htdocs\test\app\View\Users\list_users.ctp, line 40]
2016-05-23 11:40:53 Error: [FatalErrorException] Call to a member function create() on null
Request URL: /test/users/listUsers
Stack Trace:
#0 C:\xampp\htdocs\test\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 40)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 40, Array)
#2 C:\xampp\htdocs\test\lib\Cake\Core\App.php(933): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 40, Array)
#3 C:\xampp\htdocs\test\lib\Cake\Core\App.php(906): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2016-05-23 11:41:26 Error: Fatal Error (1): Call to a member function input() on null in [C:\xampp\htdocs\test\app\View\Users\list_users.ctp, line 44]
2016-05-23 11:41:26 Error: [FatalErrorException] Call to a member function input() on null
Request URL: /test/users/listUsers
Stack Trace:
#0 C:\xampp\htdocs\test\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 44)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 44, Array)
#2 C:\xampp\htdocs\test\lib\Cake\Core\App.php(933): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 44, Array)
#3 C:\xampp\htdocs\test\lib\Cake\Core\App.php(906): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2016-05-23 11:43:59 Error: Fatal Error (1): Call to a member function input() on null in [C:\xampp\htdocs\test\app\View\Users\list_users.ctp, line 44]
2016-05-23 11:43:59 Error: [FatalErrorException] Call to a member function input() on null
Request URL: /test/users/listUsers
Stack Trace:
#0 C:\xampp\htdocs\test\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 44)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 44, Array)
#2 C:\xampp\htdocs\test\lib\Cake\Core\App.php(933): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 44, Array)
#3 C:\xampp\htdocs\test\lib\Cake\Core\App.php(906): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2016-05-23 11:44:02 Error: Fatal Error (1): Call to a member function input() on null in [C:\xampp\htdocs\test\app\View\Users\list_users.ctp, line 44]
2016-05-23 11:44:02 Error: [FatalErrorException] Call to a member function input() on null
Request URL: /test/users/listUsers
Stack Trace:
#0 C:\xampp\htdocs\test\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 44)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 44, Array)
#2 C:\xampp\htdocs\test\lib\Cake\Core\App.php(933): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 44, Array)
#3 C:\xampp\htdocs\test\lib\Cake\Core\App.php(906): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2016-05-23 12:08:06 Error: Fatal Error (4): syntax error, unexpected 'public' (T_PUBLIC) in [C:\xampp\htdocs\test\app\Controller\UsersController.php, line 235]
2016-05-23 12:08:06 Error: [FatalErrorException] syntax error, unexpected 'public' (T_PUBLIC)
Request URL: /test/users/listUsers/Search.name:ndumiso
Stack Trace:
#0 C:\xampp\htdocs\test\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 235)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 235, Array)
#2 C:\xampp\htdocs\test\lib\Cake\Core\App.php(933): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 235, Array)
#3 C:\xampp\htdocs\test\lib\Cake\Core\App.php(906): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2016-05-23 12:08:16 Error: Fatal Error (4): syntax error, unexpected 'public' (T_PUBLIC) in [C:\xampp\htdocs\test\app\Controller\UsersController.php, line 235]
2016-05-23 12:08:16 Error: [FatalErrorException] syntax error, unexpected 'public' (T_PUBLIC)
Request URL: /test/users/listUsers/
Stack Trace:
#0 C:\xampp\htdocs\test\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 235)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 235, Array)
#2 C:\xampp\htdocs\test\lib\Cake\Core\App.php(933): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 235, Array)
#3 C:\xampp\htdocs\test\lib\Cake\Core\App.php(906): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2016-05-23 12:15:40 Error: Fatal Error (4): syntax error, unexpected 'public' (T_PUBLIC) in [C:\xampp\htdocs\test\app\Controller\UsersController.php, line 233]
2016-05-23 12:15:40 Error: [FatalErrorException] syntax error, unexpected 'public' (T_PUBLIC)
Request URL: /test/users/listUsers/
Stack Trace:
#0 C:\xampp\htdocs\test\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 233)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 233, Array)
#2 C:\xampp\htdocs\test\lib\Cake\Core\App.php(933): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 233, Array)
#3 C:\xampp\htdocs\test\lib\Cake\Core\App.php(906): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2016-05-23 13:02:42 Error: Fatal Error (1): Call to a member function find() on null in [C:\xampp\htdocs\test\app\Controller\UsersController.php, line 55]
2016-05-23 13:02:42 Error: [FatalErrorException] Call to a member function find() on null
Request URL: /test/users/listUsers/Search.username:ndumiso
Stack Trace:
#0 C:\xampp\htdocs\test\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 55)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 55, Array)
#2 C:\xampp\htdocs\test\lib\Cake\Core\App.php(933): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 55, Array)
#3 C:\xampp\htdocs\test\lib\Cake\Core\App.php(906): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2016-05-23 13:31:31 Error: [MissingActionException] Action PostsController::search() could not be found.
Exception Attributes: array (
  'controller' => 'PostsController',
  'action' => 'search',
)
Request URL: /test/posts/search
Stack Trace:
#0 C:\xampp\htdocs\test\lib\Cake\Routing\Dispatcher.php(193): Controller->invokeAction(Object(CakeRequest))
#1 C:\xampp\htdocs\test\lib\Cake\Routing\Dispatcher.php(167): Dispatcher->_invoke(Object(PostsController), Object(CakeRequest))
#2 C:\xampp\htdocs\test\app\webroot\index.php(118): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#3 {main}
2016-05-23 13:32:08 Error: [MissingActionException] Action PostsController::search() could not be found.
Exception Attributes: array (
  'controller' => 'PostsController',
  'action' => 'search',
)
Request URL: /test/posts/search
Stack Trace:
#0 C:\xampp\htdocs\test\lib\Cake\Routing\Dispatcher.php(193): Controller->invokeAction(Object(CakeRequest))
#1 C:\xampp\htdocs\test\lib\Cake\Routing\Dispatcher.php(167): Dispatcher->_invoke(Object(PostsController), Object(CakeRequest))
#2 C:\xampp\htdocs\test\app\webroot\index.php(118): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#3 {main}
2016-05-23 13:34:09 Error: Fatal Error (4): syntax error, unexpected 'public' (T_PUBLIC) in [C:\xampp\htdocs\test\app\Controller\UsersController.php, line 38]
2016-05-23 13:34:09 Error: [FatalErrorException] syntax error, unexpected 'public' (T_PUBLIC)
Request URL: /test/users/listUsers/Search.username:ndumiso
Stack Trace:
#0 C:\xampp\htdocs\test\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 38)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 38, Array)
#2 C:\xampp\htdocs\test\lib\Cake\Core\App.php(933): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 38, Array)
#3 C:\xampp\htdocs\test\lib\Cake\Core\App.php(906): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2016-05-23 13:34:31 Error: Fatal Error (64): Cannot redeclare UsersController::$components in [C:\xampp\htdocs\test\app\Controller\UsersController.php, line 37]
2016-05-23 13:34:31 Error: [FatalErrorException] Cannot redeclare UsersController::$components
Request URL: /test/users/listUsers/Search.username:ndumiso
Stack Trace:
#0 C:\xampp\htdocs\test\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(64, 'Cannot redeclar...', 'C:\\xampp\\htdocs...', 37)
#1 [internal function]: ErrorHandler::handleError(64, 'Cannot redeclar...', 'C:\\xampp\\htdocs...', 37, Array)
#2 C:\xampp\htdocs\test\lib\Cake\Core\App.php(933): call_user_func('ErrorHandler::h...', 64, 'Cannot redeclar...', 'C:\\xampp\\htdocs...', 37, Array)
#3 C:\xampp\htdocs\test\lib\Cake\Core\App.php(906): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2016-05-23 14:02:50 Error: [MissingConnectionException] Database connection "Mysql" is missing, or could not be created.
Exception Attributes: array (
  'class' => 'Mysql',
  'message' => 'SQLSTATE[HY000] [2002] No connection could be made because the target machine actively refused it.
',
  'enabled' => true,
)
Request URL: /test/users/edit/23
Stack Trace:
#0 C:\xampp\htdocs\test\lib\Cake\Model\Datasource\DboSource.php(260): Mysql->connect()
#1 C:\xampp\htdocs\test\lib\Cake\Model\ConnectionManager.php(105): DboSource->__construct(Array)
#2 C:\xampp\htdocs\test\lib\Cake\Model\Model.php(3617): ConnectionManager::getDataSource('default')
#3 C:\xampp\htdocs\test\lib\Cake\Model\Model.php(1155): Model->setDataSource('default')
#4 C:\xampp\htdocs\test\lib\Cake\Model\Model.php(3644): Model->setSource('users')
#5 C:\xampp\htdocs\test\lib\Cake\Model\Model.php(3142): Model->getDataSource()
#6 C:\xampp\htdocs\test\lib\Cake\Model\Model.php(3055): Model->_findCount('before', Array)
#7 C:\xampp\htdocs\test\lib\Cake\Model\Model.php(2989): Model->buildQuery('count', Array)
#8 C:\xampp\htdocs\test\lib\Cake\Model\Model.php(2904): Model->find('count', Array)
#9 C:\xampp\htdocs\test\app\Controller\UsersController.php(124): Model->exists('23')
#10 [internal function]: UsersController->edit('23')
#11 C:\xampp\htdocs\test\lib\Cake\Controller\Controller.php(490): ReflectionMethod->invokeArgs(Object(UsersController), Array)
#12 C:\xampp\htdocs\test\lib\Cake\Routing\Dispatcher.php(193): Controller->invokeAction(Object(CakeRequest))
#13 C:\xampp\htdocs\test\lib\Cake\Routing\Dispatcher.php(167): Dispatcher->_invoke(Object(UsersController), Object(CakeRequest))
#14 C:\xampp\htdocs\test\app\webroot\index.php(118): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#15 {main}
2016-05-23 15:23:35 Error: [NotFoundException] Invalid user
Request URL: /test/users/
Stack Trace:
#0 [internal function]: UsersController->index()
#1 C:\xampp\htdocs\test\lib\Cake\Controller\Controller.php(490): ReflectionMethod->invokeArgs(Object(UsersController), Array)
#2 C:\xampp\htdocs\test\lib\Cake\Routing\Dispatcher.php(193): Controller->invokeAction(Object(CakeRequest))
#3 C:\xampp\htdocs\test\lib\Cake\Routing\Dispatcher.php(167): Dispatcher->_invoke(Object(UsersController), Object(CakeRequest))
#4 C:\xampp\htdocs\test\app\webroot\index.php(118): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#5 {main}
2016-05-23 15:31:01 Error: Fatal Error (1): Call to a member function find() on null in [C:\xampp\htdocs\test\app\Controller\UsersController.php, line 86]
2016-05-23 15:31:01 Error: [FatalErrorException] Call to a member function find() on null
Request URL: /test/users/index2
Stack Trace:
#0 C:\xampp\htdocs\test\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 86)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 86, Array)
#2 C:\xampp\htdocs\test\lib\Cake\Core\App.php(933): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 86, Array)
#3 C:\xampp\htdocs\test\lib\Cake\Core\App.php(906): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2016-05-23 15:37:08 Error: Fatal Error (1): Call to a member function find() on null in [C:\xampp\htdocs\test\app\Controller\UsersController.php, line 86]
2016-05-23 15:37:08 Error: [FatalErrorException] Call to a member function find() on null
Request URL: /test/users/index2
Stack Trace:
#0 C:\xampp\htdocs\test\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 86)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 86, Array)
#2 C:\xampp\htdocs\test\lib\Cake\Core\App.php(933): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 86, Array)
#3 C:\xampp\htdocs\test\lib\Cake\Core\App.php(906): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2016-05-23 15:39:08 Error: Fatal Error (1): Call to a member function find() on null in [C:\xampp\htdocs\test\app\Controller\UsersController.php, line 87]
2016-05-23 15:39:08 Error: [FatalErrorException] Call to a member function find() on null
Request URL: /test/users/index2
Stack Trace:
#0 C:\xampp\htdocs\test\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 87)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 87, Array)
#2 C:\xampp\htdocs\test\lib\Cake\Core\App.php(933): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 87, Array)
#3 C:\xampp\htdocs\test\lib\Cake\Core\App.php(906): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2016-05-23 15:50:47 Error: Fatal Error (1): Call to a member function find() on null in [C:\xampp\htdocs\test\app\Controller\UsersController.php, line 87]
2016-05-23 15:50:47 Error: [FatalErrorException] Call to a member function find() on null
Request URL: /test/users/index2
Stack Trace:
#0 C:\xampp\htdocs\test\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 87)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 87, Array)
#2 C:\xampp\htdocs\test\lib\Cake\Core\App.php(933): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 87, Array)
#3 C:\xampp\htdocs\test\lib\Cake\Core\App.php(906): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2016-05-23 15:50:49 Error: Fatal Error (1): Call to a member function find() on null in [C:\xampp\htdocs\test\app\Controller\UsersController.php, line 87]
2016-05-23 15:50:49 Error: [FatalErrorException] Call to a member function find() on null
Request URL: /test/users/index2
Stack Trace:
#0 C:\xampp\htdocs\test\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 87)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 87, Array)
#2 C:\xampp\htdocs\test\lib\Cake\Core\App.php(933): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 87, Array)
#3 C:\xampp\htdocs\test\lib\Cake\Core\App.php(906): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2016-05-23 15:55:44 Error: [MissingControllerException] Controller class CssController could not be found.
Exception Attributes: array (
  'class' => 'CssController',
  'plugin' => NULL,
)
Request URL: /test/css/base.css
Stack Trace:
#0 C:\xampp\htdocs\test\app\webroot\index.php(118): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#1 {main}
2016-05-23 15:56:31 Error: [MissingControllerException] Controller class CssController could not be found.
Exception Attributes: array (
  'class' => 'CssController',
  'plugin' => NULL,
)
Request URL: /test/css/base.css
Stack Trace:
#0 C:\xampp\htdocs\test\app\webroot\index.php(118): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#1 {main}
2016-05-23 15:56:52 Error: [MissingControllerException] Controller class CssController could not be found.
Exception Attributes: array (
  'class' => 'CssController',
  'plugin' => NULL,
)
Request URL: /test/css/base.css
Stack Trace:
#0 C:\xampp\htdocs\test\app\webroot\index.php(118): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#1 {main}
2016-05-23 15:57:13 Error: [MissingControllerException] Controller class CssController could not be found.
Exception Attributes: array (
  'class' => 'CssController',
  'plugin' => NULL,
)
Request URL: /test/css/base.css
Stack Trace:
#0 C:\xampp\htdocs\test\app\webroot\index.php(118): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#1 {main}
2016-05-23 18:04:19 Error: [MissingControllerException] Controller class CssController could not be found.
Exception Attributes: array (
  'class' => 'CssController',
  'plugin' => NULL,
)
Request URL: /test/css/base.css
Stack Trace:
#0 C:\xampp\htdocs\test\app\webroot\index.php(118): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#1 {main}
2016-05-23 18:07:34 Error: [MissingControllerException] Controller class CssController could not be found.
Exception Attributes: array (
  'class' => 'CssController',
  'plugin' => NULL,
)
Request URL: /test/css/base.css
Stack Trace:
#0 C:\xampp\htdocs\test\app\webroot\index.php(118): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#1 {main}
2016-05-23 18:08:07 Error: [MissingControllerException] Controller class CssController could not be found.
Exception Attributes: array (
  'class' => 'CssController',
  'plugin' => NULL,
)
Request URL: /test/css/base.css
Stack Trace:
#0 C:\xampp\htdocs\test\app\webroot\index.php(118): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#1 {main}
2016-05-23 18:09:47 Error: [MissingControllerException] Controller class CssController could not be found.
Exception Attributes: array (
  'class' => 'CssController',
  'plugin' => NULL,
)
Request URL: /test/css/base.css
Stack Trace:
#0 C:\xampp\htdocs\test\app\webroot\index.php(118): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#1 {main}
2016-05-23 18:10:02 Error: [MissingControllerException] Controller class CssController could not be found.
Exception Attributes: array (
  'class' => 'CssController',
  'plugin' => NULL,
)
Request URL: /test/css/base.css
Stack Trace:
#0 C:\xampp\htdocs\test\app\webroot\index.php(118): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#1 {main}
2016-05-23 18:10:14 Error: [MissingControllerException] Controller class CssController could not be found.
Exception Attributes: array (
  'class' => 'CssController',
  'plugin' => NULL,
)
Request URL: /test/css/base.css
Stack Trace:
#0 C:\xampp\htdocs\test\app\webroot\index.php(118): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#1 {main}
2016-05-23 18:36:20 Error: [MissingControllerException] Controller class CssController could not be found.
Exception Attributes: array (
  'class' => 'CssController',
  'plugin' => NULL,
)
Request URL: /test/css/base.css
Stack Trace:
#0 C:\xampp\htdocs\test\app\webroot\index.php(118): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#1 {main}
2016-05-23 18:36:37 Error: [MissingControllerException] Controller class CssController could not be found.
Exception Attributes: array (
  'class' => 'CssController',
  'plugin' => NULL,
)
Request URL: /test/css/base.css
Stack Trace:
#0 C:\xampp\htdocs\test\app\webroot\index.php(118): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#1 {main}
2016-05-23 18:40:33 Error: [MissingControllerException] Controller class CssController could not be found.
Exception Attributes: array (
  'class' => 'CssController',
  'plugin' => NULL,
)
Request URL: /test/css/base.css
Stack Trace:
#0 C:\xampp\htdocs\test\app\webroot\index.php(118): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#1 {main}
2016-05-23 18:40:49 Error: [MissingControllerException] Controller class CssController could not be found.
Exception Attributes: array (
  'class' => 'CssController',
  'plugin' => NULL,
)
Request URL: /test/css/base.css
Stack Trace:
#0 C:\xampp\htdocs\test\app\webroot\index.php(118): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#1 {main}
2016-05-23 18:41:34 Error: Fatal Error (1): Call to a member function create() on null in [C:\xampp\htdocs\test\app\View\Users\search.ctp, line 1]
2016-05-23 18:41:34 Error: [FatalErrorException] Call to a member function create() on null
Request URL: /test/users/search/page:1/search:ndumiso
Stack Trace:
#0 C:\xampp\htdocs\test\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 1)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 1, Array)
#2 C:\xampp\htdocs\test\lib\Cake\Core\App.php(933): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 1, Array)
#3 C:\xampp\htdocs\test\lib\Cake\Core\App.php(906): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2016-05-23 19:09:23 Error: [NotFoundException] Not Found
Request URL: /test/users/listUsers/page:2
Stack Trace:
#0 C:\xampp\htdocs\test\app\Controller\UsersController.php(43): PaginatorComponent->paginate()
#1 [internal function]: UsersController->listUsers()
#2 C:\xampp\htdocs\test\lib\Cake\Controller\Controller.php(490): ReflectionMethod->invokeArgs(Object(UsersController), Array)
#3 C:\xampp\htdocs\test\lib\Cake\Routing\Dispatcher.php(193): Controller->invokeAction(Object(CakeRequest))
#4 C:\xampp\htdocs\test\lib\Cake\Routing\Dispatcher.php(167): Dispatcher->_invoke(Object(UsersController), Object(CakeRequest))
#5 C:\xampp\htdocs\test\app\webroot\index.php(118): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#6 {main}
2016-05-23 19:09:31 Error: [NotFoundException] Not Found
Request URL: /test/users/listUsers/page:2
Stack Trace:
#0 C:\xampp\htdocs\test\app\Controller\UsersController.php(43): PaginatorComponent->paginate()
#1 [internal function]: UsersController->listUsers()
#2 C:\xampp\htdocs\test\lib\Cake\Controller\Controller.php(490): ReflectionMethod->invokeArgs(Object(UsersController), Array)
#3 C:\xampp\htdocs\test\lib\Cake\Routing\Dispatcher.php(193): Controller->invokeAction(Object(CakeRequest))
#4 C:\xampp\htdocs\test\lib\Cake\Routing\Dispatcher.php(167): Dispatcher->_invoke(Object(UsersController), Object(CakeRequest))
#5 C:\xampp\htdocs\test\app\webroot\index.php(118): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#6 {main}
2016-05-23 19:18:50 Error: [NotFoundException] Not Found
Request URL: /test/users/listUsers/page:2/search:xmbete
Stack Trace:
#0 C:\xampp\htdocs\test\app\Controller\UsersController.php(43): PaginatorComponent->paginate()
#1 [internal function]: UsersController->listUsers()
#2 C:\xampp\htdocs\test\lib\Cake\Controller\Controller.php(490): ReflectionMethod->invokeArgs(Object(UsersController), Array)
#3 C:\xampp\htdocs\test\lib\Cake\Routing\Dispatcher.php(193): Controller->invokeAction(Object(CakeRequest))
#4 C:\xampp\htdocs\test\lib\Cake\Routing\Dispatcher.php(167): Dispatcher->_invoke(Object(UsersController), Object(CakeRequest))
#5 C:\xampp\htdocs\test\app\webroot\index.php(118): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#6 {main}
2016-05-23 19:21:11 Error: [NotFoundException] Not Found
Request URL: /test/users/listUsers/page:2/search:xmbete
Stack Trace:
#0 C:\xampp\htdocs\test\app\Controller\UsersController.php(43): PaginatorComponent->paginate()
#1 [internal function]: UsersController->listUsers()
#2 C:\xampp\htdocs\test\lib\Cake\Controller\Controller.php(490): ReflectionMethod->invokeArgs(Object(UsersController), Array)
#3 C:\xampp\htdocs\test\lib\Cake\Routing\Dispatcher.php(193): Controller->invokeAction(Object(CakeRequest))
#4 C:\xampp\htdocs\test\lib\Cake\Routing\Dispatcher.php(167): Dispatcher->_invoke(Object(UsersController), Object(CakeRequest))
#5 C:\xampp\htdocs\test\app\webroot\index.php(118): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#6 {main}
2016-06-01 17:16:25 Error: [NotFoundException] Not Found
Request URL: /test/membership/users/listUsers/page:2
Stack Trace:
#0 C:\Users\nmbete\Desktop\mysql\htdocs\test\membership\app\Controller\UsersController.php(43): PaginatorComponent->paginate()
#1 [internal function]: UsersController->listUsers()
#2 C:\Users\nmbete\Desktop\mysql\htdocs\test\membership\lib\Cake\Controller\Controller.php(490): ReflectionMethod->invokeArgs(Object(UsersController), Array)
#3 C:\Users\nmbete\Desktop\mysql\htdocs\test\membership\lib\Cake\Routing\Dispatcher.php(193): Controller->invokeAction(Object(CakeRequest))
#4 C:\Users\nmbete\Desktop\mysql\htdocs\test\membership\lib\Cake\Routing\Dispatcher.php(167): Dispatcher->_invoke(Object(UsersController), Object(CakeRequest))
#5 C:\Users\nmbete\Desktop\mysql\htdocs\test\membership\app\webroot\index.php(118): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#6 {main}
